services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/Documents/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_name
      MONGO_INITDB_ROOT_PASSWORD: db_psd
